:root{--bg:#050505;--panel:#111214;--panel2:#17191c;--line:#303238;--white:#f7f7f7;--muted:#b7bcc5;--red:#df171d;--red-dark:#9f0f14;--gold:#f7c948;--shadow:0 20px 60px rgba(0,0,0,.45);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;color:var(--white);background:linear-gradient(rgba(0,0,0,.82),rgba(0,0,0,.92)),radial-gradient(circle at 15% 10%,rgba(223,23,29,.18),transparent 28%),linear-gradient(135deg,#050505,#0c0d10 60%,#050505);background-attachment:fixed}a{text-decoration:none;color:inherit}button,input,select,textarea{font:inherit}
.topbar{position:sticky;top:0;z-index:50;display:flex;align-items:center;justify-content:space-between;gap:22px;padding:10px max(24px,calc((100vw - 1440px)/2));background:rgba(0,0,0,.96);border-bottom:1px solid rgba(255,255,255,.09);backdrop-filter:blur(18px)}
.brand{display:flex;align-items:center}.officialLogo{width:250px;height:82px;object-fit:contain;object-position:left center;background:#000}.topbar nav{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.topbar nav a{padding:11px 13px;border-radius:8px;font-size:.88rem;font-weight:800;text-transform:uppercase;letter-spacing:.02em;color:#e7e7e7;white-space:nowrap;display:flex;align-items:center;gap:5px}.topbar nav a:hover,.topbar nav a.active{color:#fff;background:rgba(255,255,255,.07);box-shadow:inset 0 -2px 0 var(--red)}
.page{width:min(1440px,calc(100% - 32px));margin:0 auto;padding:24px 0 70px}.hero{min-height:650px;display:grid;grid-template-columns:1.15fr .85fr;align-items:center;gap:32px;padding:70px 68px;border:1px solid rgba(255,255,255,.08);background:linear-gradient(90deg,rgba(0,0,0,.97) 0%,rgba(0,0,0,.78) 38%,rgba(0,0,0,.38) 68%,rgba(0,0,0,.25) 100%),url('/hero-car-clean.jpg') right center/cover no-repeat;box-shadow:var(--shadow);overflow:hidden;position:relative}.hero:before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(135deg,rgba(223,23,29,.10),transparent 32%),linear-gradient(180deg,transparent 70%,rgba(0,0,0,.45))}.hero>div,.glassCard{position:relative;z-index:2}.eyebrow{display:inline-block;color:var(--red);font-weight:1000;letter-spacing:.06em;text-transform:uppercase;font-size:.95rem}.hero h1,.title h1,.dashboardHead h1{margin:16px 0;font-size:clamp(3rem,6.5vw,6rem);line-height:.98;letter-spacing:-.035em;text-transform:uppercase;font-style:italic}.hero h1 em{color:var(--red);font-style:italic}.hero p,.title p{max-width:720px;color:#ddd;line-height:1.7;font-size:1.08rem}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:48px;padding:13px 20px;border-radius:6px;border:1px solid rgba(255,255,255,.2);font-weight:900;text-transform:uppercase;cursor:pointer}.primary{background:linear-gradient(145deg,var(--red),var(--red-dark));color:#fff;border-color:transparent;box-shadow:0 12px 28px rgba(223,23,29,.25)}.primary:disabled{opacity:.55;cursor:not-allowed}.secondary{background:rgba(0,0,0,.44);color:#fff}.glassCard{justify-self:end;width:min(100%,340px);padding:26px;border-radius:12px;background:rgba(5,6,8,.82);border:1px solid rgba(255,255,255,.17);box-shadow:0 18px 45px rgba(0,0,0,.42);backdrop-filter:blur(8px)}.glassCard strong{color:var(--red);font-size:1.8rem}.glassCard p{color:#c6cbd3}.glassCard hr{border:0;border-top:1px solid rgba(255,255,255,.14);margin:18px 0}
.featureGrid,.dashboardGrid,.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}.featureGrid article,.dashCard,.stats article,.panel,.listItem{background:linear-gradient(180deg,rgba(24,25,28,.97),rgba(12,13,15,.98));color:#fff;border:1px solid #303238;box-shadow:var(--shadow)}.featureGrid article,.dashCard,.stats article{padding:24px;border-radius:12px;position:relative;overflow:hidden}.featureGrid article:before,.dashCard:before{content:"";position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,var(--red),transparent)}.featureGrid h3,.dashCard h3{margin:0 0 8px;text-transform:uppercase}.featureGrid p,.dashCard p,.stats span,.listItem p{color:var(--muted);line-height:1.6}.dashCard.admin{border-color:rgba(223,23,29,.55)}
.title{padding:32px 0 20px}.title h1{font-size:clamp(2.5rem,5vw,4.6rem)}.panel{padding:28px;border-radius:14px}.formGrid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.wide{grid-column:1/-1}label{display:flex;flex-direction:column;gap:8px;font-size:.9rem;font-weight:900;text-transform:uppercase;letter-spacing:.02em}input,select,textarea{width:100%;border:1px solid #353941;border-radius:7px;padding:13px 14px;background:#0b0c0f;color:#fff}input:focus,select:focus,textarea:focus{outline:2px solid rgba(223,23,29,.35);border-color:var(--red)}.notice{padding:15px 17px;border-radius:8px;background:rgba(223,23,29,.1);border:1px solid rgba(223,23,29,.35);color:#ffd5d7}.uploadList{display:flex;flex-wrap:wrap;gap:8px}.uploadList span{padding:8px 10px;border-radius:7px;background:#202227;color:#e6e8eb;font-size:.85rem}
.trackFields{display:grid;grid-template-columns:1fr 1fr auto;align-items:end;gap:12px}.trackButton{min-height:46px}.trackingResult{margin-top:18px;padding:20px;border:1px solid var(--line);border-left:4px solid var(--red);border-radius:9px;background:#0b0c0e}.trackingResult h2{margin:8px 0 12px}.trackingResult p{color:#c9ced6}.record{white-space:pre-wrap;background:#090a0c;padding:14px;border-radius:8px}.login{max-width:440px;margin:60px auto;display:grid;gap:14px;text-align:center}.brandMark{width:54px;height:54px;border-radius:12px;display:inline-grid;place-items:center;background:linear-gradient(145deg,var(--red),#991b1b);font-weight:1000;margin:auto}.brandMark.large{width:78px;height:78px;font-size:1.8rem}
.dashboardHead{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:20px}.dashboardHead h1{font-size:clamp(2.5rem,5vw,4rem)}.list{display:flex;flex-direction:column;gap:12px}.listItem{padding:18px;border-radius:10px;display:flex;justify-content:space-between;align-items:center;gap:16px;border-left:4px solid var(--red)}.listItem h3{margin:0 0 6px}.listItem span{display:inline-block;padding:6px 10px;border-radius:999px;background:#202227;font-size:.76rem;font-weight:900}.photoGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:10px}.photoTile{padding:16px;border:1px dashed #555;background:#0b0c0e;border-radius:7px}.stats{grid-template-columns:repeat(4,1fr)}.stats strong{display:block;font-size:1.8rem}.stats span{text-transform:uppercase;font-size:.78rem}footer{border-top:1px solid rgba(255,255,255,.08);padding:28px;text-align:center;color:#9ea4ad;background:#050505}
@media(max-width:1000px){.topbar{position:static;flex-direction:column;align-items:flex-start}.topbar nav{width:100%;overflow:auto;flex-wrap:nowrap}.hero{grid-template-columns:1fr;padding:42px;background-position:65% center}.glassCard{justify-self:start}.stats{grid-template-columns:repeat(2,1fr)}}
@media(max-width:650px){.page{width:min(100% - 18px,1440px);padding-top:12px}.officialLogo{width:190px;height:64px}.hero{min-height:auto;padding:28px 20px;background:linear-gradient(90deg,rgba(0,0,0,.96),rgba(0,0,0,.72)),url('/hero-car-clean.jpg') 62% center/cover no-repeat}.hero h1{font-size:clamp(2.7rem,14vw,4.2rem)}.glassCard{width:100%}.featureGrid,.dashboardGrid,.formGrid,.trackFields,.stats{grid-template-columns:1fr}.wide{grid-column:auto}.dashboardHead{align-items:flex-start;flex-direction:column}.listItem{align-items:flex-start;flex-direction:column}.trackButton{width:100%}}

.languageSelector{
  display:flex;
  flex-direction:row;
  align-items:center;
  gap:7px;
  padding:5px 8px;
  border:1px solid rgba(255,255,255,.18);
  border-radius:8px;
  background:#111317;
  text-transform:none;
  letter-spacing:0;
  font-size:.78rem;
  white-space:nowrap;
}
.languageSelector span{color:#bfc5ce;font-weight:800}
.languageSelector select{
  width:auto;
  min-width:105px;
  padding:7px 9px;
  border:0;
  background:#08090b;
  color:#fff;
  font-size:.82rem;
}
@media(max-width:650px){
  .languageSelector{position:sticky;left:0}
  .languageSelector span{display:none}
}
.bookingSteps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:16px}.bookingStep{display:flex;align-items:center;gap:10px;padding:13px 15px;border:1px solid var(--line);border-radius:9px;background:#0b0c0e;color:#777e88}.bookingStep span{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:#24262b;color:#c5cad2;font-weight:1000}.bookingStep.active{border-color:rgba(223,23,29,.7);color:#fff}.bookingStep.active span{background:var(--red);color:#fff}.bookingPanel{display:grid;gap:0}.bookingSection{padding:4px 0 24px}.bookingSection+.bookingSection{border-top:1px solid var(--line);padding-top:24px}.bookingSectionHead{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:16px}.bookingSectionHead h2{margin:5px 0 0;text-transform:uppercase}.compact{padding:9px 12px;min-height:auto}.datePicker{width:min(100%,420px);min-height:52px;font-size:1.05rem}.timeGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.timeSlot{min-height:82px;display:flex;flex-direction:column;justify-content:center;gap:5px;border:1px solid #3a3d43;border-radius:8px;background:#0a0b0d;color:#fff;cursor:pointer}.timeSlot small{color:#9da4ae}.timeSlot:hover:not(:disabled),.timeSlot.selected{border-color:var(--red);background:rgba(223,23,29,.12)}.timeSlot:disabled{opacity:.36;cursor:not-allowed}.selectedAppointment{margin:8px 0 0;color:#c9ced6;font-weight:800}.bookingMessage{margin-top:0}@media(max-width:850px){.timeGrid{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.bookingSteps{grid-template-columns:1fr}.bookingSectionHead{flex-direction:column}.timeGrid{grid-template-columns:1fr 1fr}}
